baseURL = 'https://salomegf.github.io/blog-labveiltech/'
# baseURL = '/'
languageCode = 'en-us'
title = 'Salomé Gfeller'
theme = "hugo-theme-hello-friend-master"
paginate = 5
enableEmoji = true

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  # defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  # (default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Salomé Gfeller"
    subtitle = "Un blog"
    keywords = ""
    copyright = ""
    menuMore = "Voir plus"
    writtenBy = "Écrit par"
    readMore = "Lire la suite"
    readOtherPosts = "Lire d'autres articles"
    newerPosts = "Articles plus récents"
    olderPosts = "Articles plus anciens"
    minuteReadingTime = "min de lecture"
    dateFormatSingle = "02.01.2006"
    dateFormatList = "02.01.2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "salomé gfeller"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "à propos"
        name = "À propos"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"